services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    networks:
      - backend
    volumes:
      - type: bind
        source: ./data
        target: /data/db
  be:
    image: be
    build: ./invite-be
    networks:
      - frontend
      - backend
    ports:
      - 3000:3000
    depends_on:
      - mongodb
  fe:
    image: fe
    build: ./invite
    networks:
      - frontend
    ports:
      - 443:443
    depends_on:
      - be
networks:
  backend:
    name: backend
    driver: bridge
  frontend:
    name: frontend
    driver: bridge